from enum import Enum


class MonkeyEnum(Enum):
    DART_MONKEY = 0
    BOOMERANG_MONKEY = 1
    BOMB_SHOOTER = 2
    TACK_SHOOTER = 3
    ICE_MONKEY = 4
    GLUE_GUNNER = 5
    SNIPER_MONKEY = 6
    MONKEY_SUB = 7
    MONKEY_BUCANEER = 8
    MONKEY_ACE = 9
    HELI_PILOT = 10
    MORTAR_MONKEY = 11
    DARTLING_GUNNER = 12
    WIZARD_MONKEY = 13
    SUPER_MONKEY = 14
    NINJA_MONKEY = 15
    ALCHEMIST = 16
    DRUID = 17
    BANANA_FARM = 18
    ENGINEER_MONKEY = 19
    SPIKE_FACTORY = 20
    MONKEY_VILLAGE = 21
    HEROES = 22
