import os

GAME_DATA_DIR = "game_data"
SNIPPETS_DIR = os.path.join(GAME_DATA_DIR, "snippets")
SNIPPET_INFO_PATH = os.path.join(GAME_DATA_DIR, 'snippet_info.json')
SNIPPET_TYPES_PATH = os.path.join(GAME_DATA_DIR, 'snippet_types.json')

GAME_X1: int = 0
GAME_Y1: int = 0
GAME_WIDTH: int = 1920
GAME_HEIGHT: int = 1080
GAME_X2: int = GAME_X1 + GAME_WIDTH
GAME_Y2: int = GAME_Y1 + GAME_HEIGHT

STANDARD_X1: int = 0
STANDARD_Y1: int = 0
STANDARD_WIDTH: int = 800
STANDARD_HEIGHT: int = STANDARD_WIDTH * GAME_HEIGHT // GAME_WIDTH
STANDARD_X2: int = STANDARD_X1 + STANDARD_WIDTH
STANDARD_Y2: int = STANDARD_Y1 + STANDARD_HEIGHT

MONITOR_X1: int = 0
MONITOR_Y1: int = 0
MONITOR_WIDTH: int = 1920
MONITOR_HEIGHT: int = 1080
MONITOR_X2: int = MONITOR_X1 + MONITOR_WIDTH
MONITOR_Y2: int = MONITOR_Y1 + MONITOR_HEIGHT