from enum import Enum

class SnippetEnum(Enum):
    # Basic
    TITLE = -1
    MAIN = 0
    SETTINGS = 1
    JUKEBOX = 2
    ACCOUNT_SETTINGS = 3
    LANGUAGE_SETTINGS = 4
    HOTKEYS = 5
    UPDATE_NOTES = 6
    CREATOR_SUPPORT = 7
    TWITCH_INTEGRATION = 8
    SCREEN_SIZE = 9
    ACHIEVEMENTS = 10
    SHOP = 11
    TROPHY_STORE = 12
    INVENTORY = 13
    DAILY_REWARD = 14
    FRIENDS = 15
    POWERS = 16
    INSTA_MONKEYS = 17
    MONKEY_KNOWLEDGE = 18
    PRIMARY_KNOWLEDGE = 19
    MILITARY_KNOWLEDGE = 20
    MAGIC_KNOWLEDGE = 21
    SUPPORT_KNOWLEDGE = 22
    HEROES_KNOWLEDGE = 23
    POWERS_KNOWLEDGE = 24
    
    # Group Monkey Upgrade screens
    PRIMARY_MONKEYS = 25
    MILITARY_MONKEYS = 26
    MAGIC_MONKEYS = 27
    SUPPORT_MONKEYS = 28

    # Individual Monkey Upgrades
    DART_MONKEY_UPGRADE = 29
    BOOMERANG_MONKEY_UPGRADE = 30
    BOMB_SHOOTER_UPGRADE = 31
    TACK_SHOOTER_UPGRADE = 32
    ICE_MONKEY_UPGRADE = 33
    GLUE_GUNNER_UPGRADE = 34
    SNIPER_MONKEY_UPGRADE = 35
    MONKEY_SUB_UPGRADE = 36
    MONKEY_BUCANEER_UPGRADE = 37
    MONKEY_ACE_UPGRADE = 38
    HELI_PILOT_UPGRADE = 39
    MORTAR_MONKEY_UPGRADE = 40
    DARTLING_GUNNER_UPGRADE = 41
    WIZARD_MONKEY_UPGRADE = 42
    SUPER_MONKEY_UPGRADE = 43
    NINJA_MONKEY_UPGRADE = 44
    ALCHEMIST_UPGRADE = 45
    DRUID_UPGRADE = 46
    BANANA_FARM_UPGRADE = 47
    ENGINEER_MONKEY_UPGRADE = 48
    SPIKE_FACTORY_UPGRADE = 49
    MONKEY_VILLAGE_UPGRADE = 50
    HEROES = 51
    
    # Map Groups
    BEGINNER_MAPS_0 = 52
    BEGINNER_MAPS_1 = 53
    BEGINNER_MAPS_2 = 54
    BEGINNER_MAPS_3 = 55
    INTERMEDIATE_MAPS_0 = 56
    INTERMEDIATE_MAPS_1 = 57
    INTERMEDIATE_MAPS_2 = 58
    INTERMEDIATE_MAPS_3 = 59
    ADVANCED_MAPS_0 = 60
    ADVANCED_MAPS_1 = 61
    ADVANCED_MAPS_2 = 62
    EXPERT_MAPS_0 = 63
    EXPERT_MAPS_1 = 64
 
    # Individual Maps
    MONKEY_MEADOW = 65
    TREE_STUMP = 66
    TOWN_CENTER = 67
    SCRAPYARD = 68
    THE_CABIN = 69
    RESORT = 70
    BACK_BUTTON = 71
    CHANGE_HERO_BUTTON = 72
    FRIENDS_BUTTON = 73

